### ISSUE TITLE
Fix imports

### ISSUE THREAD

**Issue by srgpdbd** [srgpdbd/js-reverse#9]

**Comment by srgpdbd** [comment]
For now imports looks like 
```
import Library from 'js-reverse/js-reverse/reverse-library';
```
But it can be shortened by just moving files to
```
import Library from 'js-reverse/reverse-library';
```

**Comment by lucas-carl** [comment]
I would put a index.js file in the project root. Then you would only need to write:
`import Library from 'js-reverse'`

But i'm not sure how you would export the Library from within that index file.
